export const languages = {
	af: 'Afrikaans',
	ar: 'Arabic (عربي)',
	az: 'Azerbaijani (Azərbaycan)',
	be: 'Belarusian (беларускі)',
	bg: 'Bulgarian (български)',
	bn: 'Bengali (বাংলা)',
	ca: 'Catalan (Català)',
	cs: 'Czech (Čeština)',
	cy: 'Welsh (Cymraeg)',
	da: 'Danish (Dansk)',
	de: 'German (Deutsch)',
	el: 'Greek (Ελληνικά)',
	en: 'English',
	es: 'Spanish (Español)',
	et: 'Estonian (Eesti keel)',
	eu: 'Basque (Euskara)',
	fa: 'Persian (فارسی)',
	fi: 'Finnish (Suomalainen)',
	fr: 'French (Français)',
	ga: 'Irish (Gaeilge)',
	gl: 'Galician (Galego)',
	gu: 'Gujarati (ગુજરાતી)',
	hi: 'Hindi (हिंदी)',
	hr: 'Croatian (Hrvatski)',
	ht: 'Haitian Creole (Kreyòl ayisyen)',
	hu: 'Hungarian (Magyar)',
	id: 'Indonesian (bahasa Indonesia)',
	is: 'Icelandic (Íslenskur)',
	it: 'Italian (Italiano)',
	iw: 'Hebrew (עִברִית)',
	ja: 'Japanese (日本語)',
	ka: 'Georgian (ქართული)',
	kn: 'Kannada (ಕನ್ನಡ)',
	ko: 'Korean (한국인)',
	la: 'Latin (Latinus)',
	lt: 'Lithuanian (Lietuvių)',
	lv: 'Latvian (Latviski)',
	mk: 'Macedonian (Македонски)',
	ms: 'Malay (Melayu)',
	nl: 'Dutch (Nederlands)',
	no: 'Norwegian (Norsk)',
	pl: 'Polish (Polski)',
	pt: 'Portuguese (Português)',
	ru: 'Russian (Русский)',
	sk: 'Slovak (Slovenský)',
	sl: 'Slovenian (Slovenščina)',
	sq: 'Albanian (Shqiptare)',
	sv: 'Swedish (Svenska)',
	sw: 'Swahili (Kiswahili)',
	ta: 'Tamil (தமிழ்)',
	te: 'Telugu (తెలుగు)',
	th: 'Thai (แบบไทย)',
	tl: 'Talagog/Filipino',
	tr: 'Turkish (Türkçe)',
	uk: 'Ukrainian (Українська)',
	ur: 'Urdu (اردو)',
	vi: 'Vietnamese (Tiếng Việt)',
	yi: 'Yiddish (יידיש)',
	'zh-CN': 'Chinese Simplified (简体中文)',
};
